/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 hexagonBar.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hexagonBar.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bar.geometry} material={nodes.bar.material} />
    </group>
  )
}

useGLTF.preload('/hexagonBar.glb')
