/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cute_plane_2.glb -T 
Files: cute_plane_2.glb [32.13MB] > D:\workspace_blender\ai可爱小飞机\cute_plane_2-transformed.glb [445.54KB] (99%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { asset } from '~/utils/asset'

export default function Model(props) {
  const { nodes, materials } = useGLTF(asset('/model/cute_plane_2-transformed.glb'))
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.node_0.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

// useGLTF.preload('/cute_plane_2-transformed.glb')
